### ISSUE TITLE
Flow (Required module not found) for Some Date Formatting Exports

### ISSUE THREAD

**Issue by doverdb12** [psirenny/md-in-js#8]
Hi Dennis,

It looks like Flow is throwing some errors due to modules that cannot be found in this project (this is a cool project, btw). There's a group of imports like  '../src/format/date-options_hour-min'; starting at line 571 in index.js.flow that should just start as './format...' from what I can tell. If I'm missing something obvious just let me know. I could branch and put up a PR if you'd like.

**Comment by psirenny** [comment]
Thanks 😄 

Good catch. I published a new version `1.17.0` that resolves this issue. Try it out and let me know if it that resolves it. I haven't been very diligent about following semver. Hopefully, there aren't any breaking changes.

**Comment by psirenny** [comment]
Actually, I think a bunch of the animation imports will break. They were changed to be functions in an effort to make them as *themeable* as possible. I can fix those if you want.

**Comment by doverdb12** [comment]
Oops, sorry, didn't realize the version difference. I switched to 1.17.0 and I'm not seeing the broken animation imports, but it's entirely possible I'm just not looking in the right place. I'd be happy to fix them if need be.

**Comment by psirenny** [comment]
Ahh that's good to hear. Yea, it looks like values the project imports were unchanged.
